### PR TITLE
Add Swift Package Manager support, update to Swift 5, remove unused files

### PR DESCRIPTION
**Pull request by Ast3r10n**
This PR will convert Rippl to a Swift Package while still retaining Cocoapods and Carthage support.

As of 2020, Swift 3 is deprecated. To allow use of Rippl, a conversion to Swift 5 was required. Using a Swift Package structure makes the library itself lighter and more reliable, as well as future-proof.

### CODE REVIEW

**Comment by jeanetienne** [comment]
@Ast3r10n Awesome, thanks! I'll review this over the weekend 👍

**Comment by jeanetienne** [comment]
Hi @Ast3r10n, thank you for your contribution!

I'm not very familiar (yet) with SwiftPM, could you explain if deleting the sample project is necessary? I think it adds value to have an example implementation?

**Comment by Ast3r10n** [comment]
> Hi @Ast3r10n, thank you for your contribution!
> 
> I'm not very familiar (yet) with SwiftPM, could you explain if deleting the sample project is necessary? I think it adds value to have an example implementation?

Hi @jeanetienne, deleting the sample project is not strictly necessary, though it is advisable. In this case, the Rippl.swift file is the only needed file here, which makes a very light Package. Having the sample project inside the Package (even if ignored by the compiler) would have no benefit to the user (since users will most likely use SPM to import Rippl) and add some weight to the Package.

I can certainly revert the sample project deletion if you prefer, but I don't really think it would be that useful.

P.s.: to make the Package even lighter, an option would be to host the README.md gifs remotely, to avoid having them inside the Package.

**Comment by Ast3r10n** [comment]
Hey there! Any news on this one?

**Comment by jeanetienne** [comment]
> Hey there! Any news on this one?

Sorry, I'm really swamped with work and other commitments. 
On the other hand I don't have plans to add features or anything major anytime soon, so you might as well work with your fork as it's probably the most up to date version of this project 👍

**Pull request closed without merging**
